import React, { useMemo } from 'react';

interface SmartTextProps {
  text: string;
  className?: string;
  as?: 'div' | 'span' | 'p' | 'h2';
}

/**
 * SmartText component that parses LaTeX delimiters and renders them as math.
 * Uses renderToString to avoid the "Quirks Mode" DOM measurement error.
 */
const SmartText: React.FC<SmartTextProps> = ({ text, className = "", as = "div" }) => {
  const Component = as;

  const renderedHtml = useMemo(() => {
    if (!text) return '';

    // We want to find matches for \[ ... \] and \( ... \)
    // and replace them with HTML generated by KaTeX.
    return text.replace(/(\\\[[\s\S]*?\\\]|\\\([\s\S]*?\\\))/g, (match) => {
      const isDisplay = match.startsWith('\\[');
      // Remove delimiters
      const content = isDisplay 
        ? match.substring(2, match.length - 2) 
        : match.substring(2, match.length - 2);
      
      try {
        if (!(window as any).katex) {
          console.warn("KaTeX not loaded yet.");
          return match;
        }
        
        return (window as any).katex.renderToString(content, {
          displayMode: isDisplay,
          throwOnError: false,
          trust: true
        });
      } catch (e) {
        console.error("KaTeX Parsing Error:", e);
        return `<span class="text-red-500 font-mono text-xs border border-red-200 p-0.5 rounded" title="Math Error">${match}</span>`;
      }
    });
  }, [text]);

  return (
    <Component 
      className={className} 
      dangerouslySetInnerHTML={{ __html: renderedHtml }} 
    />
  );
};

export default SmartText;